Repository Py-Contributors/awesomeScripts, pull requests merged in 2020-10, with the labels that each got.

#159 Added Wifi Password Getter Script
  wifi-password-getter/Readme.md
  wifi-password-getter/output.png
  wifi-password-getter/wifi_password_getter.py
Labels: hacktober-accepted

#178 creating link in readme
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  password-validator/PasswordValidation.py
  password-validator/README.md
Labels: hacktober-accepted

#267 Update dictionary.py
  english_dictionary/dictionary.py
Labels: hacktober-accepted, hacktoberfest

#274 Add script to fetch articles from Medium.com
  medium_article_scraper/LICENCE
  medium_article_scraper/README.md
  medium_article_scraper/mediumScraper.py
  medium_article_scraper/requirements.txt
Labels: hacktober-accepted, hacktoberfest

#270 Python web scrapping
  Movie recommendation script/Movie_Recommendation_Script.py
  Movie recommendation script/README.md
Labels: hacktober-accepted, hacktoberfest

#266 Initial Commit
  .DS_Store
  clock/.DS_Store
  clock/README.md
  clock/clock.py
Labels: hacktober-accepted, hacktoberfest

#283 Added code for #281
  tfHub_sentence_similarity/README.MD
  tfHub_sentence_similarity/requirements.txt
  tfHub_sentence_similarity/tfHub_sentence_similarity.py
Labels: hacktoberfest, hacktoberfest-accepted

#343 Add script for verify Github username
  check_github_username/CheckUsername.py
  check_github_username/README.md
  check_github_username/requirements.txt
Labels: hacktoberfest-accepted
